FUSETOOLS2-707 - filter out files in IDE config folders
camel-tooling/camel-language-server pull request #461
Opened 2020-09-23 08:11 UTC by apupier

when providing completion for resource-like Camel K modeline properties.

![Screenshot from 2020-09-23 10-09-51](https://user-images.githubusercontent.com/1105127/93985284-21564100-fd85-11ea-9a4c-389e7a3f4e51.png)

2020-09-23 12:30 UTC, bfitzpat commented
Would be useful to add some details on how we add more IDE specific filters or user-specific folders to the filter list

2020-09-23 12:31 UTC, bfitzpat requested changes
Would be useful to have some documentation on how these files are being filtered out -- and perhaps a way for the user to see what's being filtered in case we go too far or there are additional folders/files they want to filter out.

2020-09-23 14:20 UTC, apupier commented
> Would be useful to have some documentation on how these files are being filtered out

Can you precise which documentation you have in mind please? This is a one-liner in the code. i don't get what needs to be documented.

> and perhaps a way for the user to see what's being filtered in case we go too far or there are additional folders/files they want to filter out.

I also wondered about that. I preferred not do it for these reasons:
* I think that this PR provides enough value in most cases compared to the very rare case that is filtering out and users doesn't want. In this case, the user is not blocked anyway. He/she can still provide the value by hand.
* Providing a configurable version can be done in a separate PR. And to be leveraged it will imply to modify also each clients.
* I'm not sure that it provides enough value to provide settings to configure it. It is to target very rare case and it requires to maintain the code in several clients.

another possibility that I have in mind which avoids to requires writing code for each client, is to sort with ide folders at the end instead of completely filtering them out.

2020-09-23 14:42 UTC, bfitzpat commented
> Can you precise which documentation you have in mind please? This is a one-liner in the code. i don't get what needs to be documented.

What folders are being filtered out from the IDE side? Can you include that list in the changelog at least? Or the JIRA itself, detailing which folders are being filtered out per IDE? Though the user shouldn't be using files from these folders, it would be good to at least let users know that we are now explicitly filtering them out. 

And I get the reasons for not doing a user-provided filter at this point. I would spin that off into a separate JIRA so your rationale is at least covered in case it comes up -- and then if we get enough push back on it we can investigate the individual client changes that would have to be made to support it.

2020-09-24 06:59 UTC, apupier commented
> What folders are being filtered out from the IDE side?

ok, I thought it was documentation targeting developers.

> Can you include that list in the changelog at least?

There is no changelog provided for the Camel Language Server itself. It is used mostly continuously from snapshots and usually end-users are looking to clients and not to the server part.
There is a mention specific to VS Code in the only changelog that we are currently maintaining in this [PR](https://github.com/camel-tooling/camel-lsp-client-vscode/pull/426)

> Or the JIRA itself, detailing which folders are being filtered out per IDE? Though the user shouldn't be using files from these folders, it would be good to at least let users know that we are now explicitly filtering them out.

good point.
I will add in the readme and in the JIRA.

> And I get the reasons for not doing a user-provided filter at this point. I would spin that off into a separate JIRA so your rationale is at least covered in case it comes up -- and then if we get enough push back on it we can investigate the individual client changes that would have to be made to support it.

reported https://issues.redhat.com/browse/FUSETOOLS2-715

2020-09-24 12:32 UTC, bfitzpat approved these changes

2020-09-25 06:42 UTC, merged